### ISSUE TITLE
hugo-hooks: hand data to a filter hook and return transformed data

### ISSUE THREAD

**Issue by davidsneighbour** [davidsneighbour/hugo-blockify#20]
WordPress filter feature for GoHugo basically. Hand data to a filter(-hook) partial and if a filter partial exists for that filter term then run the data through it and return whats returned or the data unchanged.

**Comment by davidsneighbour** [comment]
Call:

```go-html-template
{{- $filteredValue := partials.Include "func/filter.html" ( collections.Dictionary 
                                            "filter" "filtername" 
                                            "context" . ) -}}
```

The required parameter is `filter` with the filter name. everything else depends on the filter and its documentation.

Configuration (copy paste from the current hooks docs):

### Module based hooks (plugin hooks)

In params.toml (or under the [params] section of the configuration) add a table array as such:

```toml
[[dnb.hooks.filters.namespace.filtername]]
file = "partial path"
weight = "integer"
cached = "boolean/string"

# proper sample
[[dnb.hooks.filters.namespace.urlfilter]]
file = "func/urlfilter.html"
weight = 100
cached = false
```

Notes:

- filtername without cached at the end. The filter must exist and be called by the calling template so that this filter is added. If the filtername does not exist, this filter will be ignored.
- weight is used for sorting filter. Please leave this out to have the filter run in the order it is added. the default weight is 0. Use this only if you want a filter run before or after others.
- cached is either a boolean defining if the result of the filter is cached per page or run every time it's called or a string. in that case, it is cached with this string as an identifier. This string might be a simple string, which will cache the result globally (NOT per page), or it might contain a %random%, which will be replaced with a random string.

Note that the cached option is a work in progress. I'll need to find ways to cache, for instance, according to section. This might change over time.-
