### ISSUE TITLE
hugo-giscus: add custom theming

### ISSUE THREAD

**Issue by davidsneighbour** [davidsneighbour/hugo-blockify#44]
As described in [Advanced Usage](https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#data-theme) a custom theme can be added. Let's implement it here too.

The setup would be as follows:

### config

```toml
[outputs]
home = ["GISCUS_THEME"]
[params.dnb.giscus]
theme = "dark"
[params.dnb.giscus.theme]
stylesheet = "scss/giscus/theme.scss"
colorPrettylightsSyntaxComment = "#768390"
colorPrettylightsSyntaxConstant = "#6cb6ff"
...
```

`stylesheet` is a path to a stylesheet (looks by default for `assets/scss/giscus/theme.scss`). This stylesheet will import the original theme selected under `giscus` (loading via getRemote), then subsequent properties under `theme` are added as overrides and exports the finished stylesheet. 

The camelcased syntax of the theme variables are corresponding to the CSS variables in [the sample theme](https://github.com/giscus/giscus/blob/main/styles/themes/custom_example.css).

The pain point here is how to map this without having to add all items to the template. I think there should be a way to transform camelcase to title-case in Hugo.

Currently I think it's a sequence like this:
- Do a replaceRE over the key (see [this regexp test](https://regex101.com/r/v7Y1GM/1))
- lower case it
- trim extra dashes - no idea why the last item in the sample adds a dash in the end

If `GISCUS_THEME` is set in the outputs, then a custom stylesheet will be linked, so a custom theme without any settings in the `theme` config section still can add custom styles via `theme.scss`.
